import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

const shell = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
const title = readFileSync(resolve(import.meta.dirname, './chat-session-title.tsx'), 'utf8')
const chat = readFileSync(resolve(import.meta.dirname, './chat-sidebar.tsx'), 'utf8')
const frame = readFileSync(resolve(import.meta.dirname, './shell-sidebar-frame.tsx'), 'utf8')
const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')

test('brand mascot lives at the corner; sidebar head is title plus collapse', () => {
  assert.match(shell, /--sidebar-flyout-width/)
  assert.match(shell, /DockSessionMascot/)
  assert.match(shell, /busy=\{busy\}/)
  assert.doesNotMatch(title, /BrandCornerMascot/)
  const approvals = readFileSync(resolve(import.meta.dirname, '../../../core-chat/src/web/approvals.tsx'), 'utf8')
  assert.match(approvals, /BrandCornerMascot/)
  assert.match(approvals, /variant="popover"/)
  assert.match(frame, /data-testid="sidebar-collapse"/)
  assert.match(frame, /app-side-bar-head-brand/)
  assert.match(frame, /SidebarBrandLockup/)
  assert.match(chat, /ShellSidebarFrame/)
  assert.match(chat, /variant === 'popover'/)
  assert.match(chat, /dock-chat-sidebar/)
  assert.match(chat, /openOverlayComposer/)
  assert.match(chat, /isChatPagePath/)
  assert.match(chat, /sessionView.load\(item.id/)
  assert.doesNotMatch(chat, /SidebarBrandMascot/)
  const mascot = readFileSync(resolve(import.meta.dirname, '../../../public-mascot/src/web/brand-mascot.tsx'), 'utf8')
  assert.doesNotMatch(mascot, /Biu Agent OS/)
  assert.match(mascot, /data-testid="brand-mascot"/)
  assert.match(mascot, /SidebarBrandLockup/)
  assert.match(mascot, /brand-agent-menu/)
  assert.match(mascot, /data-dock-tip/)
  assert.match(mascot, /data-plugin-tray/)
  assert.match(mascot, /BrandAgentMenu/)
  assert.match(mascot, /busy\?: boolean/)
  assert.match(mascot, /busy=\{busy\}/)
  assert.match(mascot, /busy=\{Boolean\(busyIds\?\.\[item\.id\]\)\}/)
  assert.match(mascot, /menu\?:/)
  assert.match(mascot, /onToggle\?:/)
  assert.match(mascot, /tapToDance/)
  assert.match(mascot, /dancing=\{tapDance\}/)
  assert.match(mascot, /CORNER_TAP_DANCE_MS/)
  assert.match(shell, /tapToDance=\{onChatPage\}/)
  assert.match(css, /brand-corner-tap-dance/)
  assert.doesNotMatch(mascot, /brand-corner-dock/)
  assert.doesNotMatch(mascot, /brand-corner-chat-overlay/)
  assert.doesNotMatch(mascot, /onToggleOverlay/)
  assert.match(shell, /ShellDockPins/)
  assert.match(shell, /if \(overlayOpen\) return null/)
  assert.match(shell, /onToggle=\{/)
  assert.match(shell, /isChatPagePath\(location.pathname\)/)
  assert.match(shell, /setChatOverlay\(true\)/)
  assert.match(shell, /overlayOpen && !showCenter/)
  assert.match(shell, /activeModule === 'agent' && getChatOverlay\(\)/)
  assert.doesNotMatch(shell, /id: 'session'/)
  assert.doesNotMatch(shell, /kind: 'session'/)
  assert.doesNotMatch(shell, /activeModule === 'agent' \? null : \(/)
  assert.doesNotMatch(shell, /activeModule !== 'agent' &&/)
  assert.doesNotMatch(shell, /\{activeModule === 'agent' \? null/)
  assert.doesNotMatch(shell, /props.renderSlot\('corner-tools'\)/)
  assert.doesNotMatch(shell, /leading=\{activeModule === 'agent' \? null/)
  assert.doesNotMatch(shell, /onToggleOverlay/)
  assert.match(css, /\.sidebar-brand-lockup\s*\{/)
  assert.doesNotMatch(css, /\.sidebar-brand-name\s*\{/)
  assert.match(css, /\.brand-corner-mascot-btn\.is-active[\s\S]*?background:\s*transparent/)
  assert.match(css, /--brand-corner-clearance:\s*1\.25rem/)
  assert.match(css, /\.session-inspector\s*\{[^}]*padding-bottom:\s*var\(--brand-corner-clearance\)/s)
  assert.match(css, /\.brand-agent-menu\s*\{[^}]*width:\s*320px/s)
  assert.match(css, /\.brand-agent-menu\s*\{[^}]*border:\s*0/s)
  assert.match(css, /\.chat-sidebar-popover\s*\{/)
  // 选中行仍靠 ::before 铺一层底色，但底色随主题走，只断言它被设置。
  assert.match(
    css,
    /\.chat-sidebar-popover \.chat-session-row\.is-active::before\s*\{[^}]*background:\s*[^;]+;/s,
  )
  assert.doesNotMatch(css, /\.os-dock-tile svg\s*\{/)
  assert.doesNotMatch(css, /\.brand-agent-menu svg[\s\S]{0,80}unset/)
  assert.doesNotMatch(css, /\.os-dock\s*\{/)
  assert.doesNotMatch(css, /\.os-dock-shelf-row/)
  assert.match(css, /\.chat-session-row-delete svg,\s*\.chat-session-row-star svg\s*\{[^}]*width:\s*16px/s)
  assert.match(css, /\.brand-corner-cluster\s*\{[^}]*right:\s*16px/s)
  assert.match(css, /\.brand-corner-cluster\s*\{[^}]*bottom:\s*16px/s)
  assert.match(css, /\.chat-dock-toolbar \.brand-corner-cluster\s*\{[^}]*position:\s*relative/s)
  assert.match(css, /\.brand-corner-cluster\s*\{[^}]*z-index:\s*200/s)
  assert.doesNotMatch(css, /\.os-dock \.brand-corner-cluster/)
  // 头部这几处文字必须同属前景色 token，断言引用关系而不是当前主题的色值。
  assert.match(css, /\.chat-view-header-expand\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
  assert.match(css, /\.chat-view-header-expand:hover\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
  assert.match(css, /\.chat-view-header-expand\.is-active\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
  assert.match(css, /\.chat-view-project\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
  assert.match(css, /\.chat-view-session-title\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
  assert.match(css, /\.chat-overlay-panel \.chat-view-header\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
  assert.match(css, /\.inspector-tab\s*\{[^}]*color:\s*var\(--dsw-label\)/s)
})

test('shell columns stay three tracks without animating on window resize', () => {
  assert.doesNotMatch(css, /\.app-shell-agent\s*\{[^}]*transition:\s*grid-template-columns/s)
  assert.doesNotMatch(css, /\.app-shell-module\s*\{[^}]*transition:\s*grid-template-columns/s)
  assert.match(
    css,
    /\.app-shell-agent\s*\{[^}]*grid-template-columns:\s*var\(--sidebar-col, 0px\) minmax\(0, 1fr\) var\(--inspector-width, 0px\)/s,
  )
  assert.match(css, /\.app-shell-agent\.is-window-resizing\s*\{[^}]*transition:\s*none/s)
  assert.match(css, /\.app-shell-module\.is-window-resizing\s*\{[^}]*transition:\s*none/s)
  assert.doesNotMatch(css, /\.app-shell-agent\.is-sidebar-collapsed\s*\{/)
  assert.match(frame, /is-closed flex/)
  assert.match(frame, /is-flyout-open/)
  assert.match(frame, /sidebar-flyout-host/)
  assert.match(frame, /isSidebarFlyoutIgnoreTarget/)
  assert.match(frame, /sidebar-edge-hot/)
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed \.app-side-bar\.is-closed\s*\{[^}]*top:\s*60px/s)
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed \.app-side-bar\.is-closed\s*\{[^}]*bottom:\s*60px/s)
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed\s*\{[^}]*width:\s*0/s)
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed\s*\{[^}]*position:\s*relative/s)
  assert.doesNotMatch(css, /\.sidebar-flyout-host\.is-collapsed\s*\{[^}]*position:\s*fixed/s)
  assert.match(css, /\.app-shell-agent > main\s*\{[^}]*grid-column:\s*2/s)
  assert.match(css, /\.app-shell-agent > \.session-inspector\s*\{[^}]*grid-column:\s*3/s)
  assert.match(css, /\.sidebar-edge-hot\s*\{[^}]*width:\s*20px/s)
  assert.match(css, /\.sidebar-edge-hot\s*\{[^}]*top:\s*22vh/s)
  assert.match(css, /\.sidebar-edge-hot\s*\{[^}]*height:\s*20vh/s)
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed\.is-flyout-open \.sidebar-edge-hot\s*\{[^}]*width:\s*var\(--sidebar-flyout-width/s)
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed \.app-side-bar\.is-closed\s*\{[^}]*z-index:\s*81/s)
  assert.match(
    css,
    /\.sidebar-flyout-host\.is-collapsed \.app-side-bar\.is-closed\s*\{[^}]*transition:\s*transform 0s linear 240ms, opacity 0s linear 240ms, pointer-events 0s linear 240ms/s,
  )
  assert.match(css, /\.sidebar-flyout-host\.is-collapsed\.is-flyout-open \.app-side-bar\.is-closed\s*\{[^}]*transition:\s*none/s)
  assert.doesNotMatch(css, /\.sidebar-flyout-host\.is-collapsed:focus-within/)
  assert.doesNotMatch(css, /\.sidebar-flyout-host\.is-collapsed:hover\s*\{[^}]*width:\s*var\(--sidebar-flyout-width/)
  assert.match(css, /\.app-side-bar\s*\{[^}]*min-width:\s*0/s)
  assert.doesNotMatch(css, /\.app-side-bar\s*\{[^}]*min-width:\s*var\(--dsw-sidebar-min\)/s)
  assert.match(css, /\.app-side-bar\.is-closed,\s*\.session-inspector\.is-closed\s*\{[^}]*min-width:\s*0/s)
})
