/**
 * 粘性用户消息不得压过底部输入栏 / dock 悬浮控件。
 * sticky 的 z-index 写在 thread 组件 Tailwind 上（z-[1]）；
 * .chat-composer-dock 用更高的 z-index 保证机轴最顶。
 */
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = resolve(import.meta.dirname, '../../../..')

describe('composer dock stacking above sticky user', () => {
  it('isolates chat-stage and keeps composer-dock above sticky user z-index', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const shell = readFileSync(resolve(root, 'packages/web-app-shell/src/web/index.tsx'), 'utf8')
    const thread = readFileSync(resolve(root, 'packages/core-chat/src/web/thread.tsx'), 'utf8')

    expect(css).toMatch(/--dsw-chat-font-size:\s*14px/)
    expect(css).toMatch(/--dsw-chat-composer-font-size:\s*14px/)
    expect(css).toMatch(/--font-sans:\s*ui-sans-serif/)
    expect(css).toMatch(/\.chat-stage\s*\{[^}]*font-family:\s*var\(--font-sans\)/s)
    expect(css).toMatch(/\.composer-tiptap\.is-readonly\s*\{[^}]*font-size:\s*var\(--dsw-chat-font-size\)/s)
    expect(css).toMatch(/\.chat-stage\s*\{[^}]*isolation:\s*isolate/s)
    expect(css).toMatch(/\.chat-select-bubble\s*\{[^}]*position:\s*fixed/s)
    expect(css).toMatch(/\.chat-composer-dock\s*\{[^}]*z-index:\s*20/s)
    expect(thread).toMatch(/sticky top-0 z-1 bg-transparent/)
    expect(thread).not.toMatch(/Running/)
    expect(thread).not.toMatch(/StatusRow/)
    expect(shell).toContain('chat-composer-dock')
    expect(shell).toContain('px-[64px]')
    expect(shell).toContain('pb-[calc(1rem+5px)]')
    expect(shell).not.toMatch(/md:px-8|lg:px-10/)
    expect(shell).not.toMatch(/bottom-0 z-\[2\]/)
    expect(css).toMatch(/html:not\(\.dark\) \.composer-send,\s*\nhtml:not\(\.dark\) \.composer-send:disabled\s*\{[^}]*color:\s*#5f5e5a/s)
    expect(css).toMatch(/html\.dark \.composer-send,\s*\nhtml\.dark \.composer-send:disabled\s*\{[^}]*background:\s*var\(--dsw-label\)/s)
    expect(css).toMatch(/html\.dark \.composer-send,\s*\nhtml\.dark \.composer-send:disabled\s*\{[^}]*border:\s*1px solid var\(--dsw-label\)/s)
  })

  it('compose-only overlay hides the reply thread until send', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/core-chat/src/web/composer.tsx'), 'utf8')
    expect(css).toMatch(/\.chat-overlay-panel \{/)
    expect(css).toMatch(/\.chat-overlay-panel\.is-compose-only \.chat-overlay-thread\s*\{[^}]*display:\s*none/s)
    expect(css).toMatch(/\.chat-overlay-panel\.is-compose-only \.chat-overlay-head\s*\{[^}]*display:\s*none/s)
    expect(css).toMatch(/\.chat-overlay-panel\.is-compose-only\s*\{[^}]*background:\s*transparent/s)
    expect(css).toMatch(/\.chat-overlay-panel\.is-compose-only\s*\{[^}]*border:\s*0/s)
    const overlayWin = readFileSync(resolve(root, 'packages/web-app-shell/src/web/overlay-window.tsx'), 'utf8')
    expect(overlayWin).toMatch(/threadOpen \? \(/)
    expect(overlayWin).toContain('chat-overlay-head')
    expect(css).not.toMatch(/chat-overlay-peek/)
    expect(composer).toContain('revealOverlayThread')
    expect(composer).toContain('composer-goal')
    expect(composer).toContain("controlGoal('pause')")
    expect(composer).toContain("controlGoal('clear')")
    expect(composer).toContain('isComposerFocusPending')
    expect(composer).toContain('biu:composer-focus')
  })

  it('shows an interruptible Goal bar above the composer', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/core-chat/src/web/composer.tsx'), 'utf8')
    expect(composer).toContain('composer-goal')
    expect(composer).toContain('PauseIcon')
    expect(composer).toContain('PlayIcon')
    expect(composer).toContain('XMarkIcon')
    expect(composer).toContain('FlagIcon')
    expect(composer).toContain("aria-label=\"暂停 Goal\"")
    expect(composer).toContain("aria-label=\"清除 Goal\"")
    expect(composer).not.toMatch(/composer-goal-btn[^>]*>\s*暂停/)
    expect(css).toMatch(/\.composer-goal-btn\s*\{[^}]*width:\s*28px/s)
    expect(css).toMatch(/\.composer-goal\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).not.toMatch(/\.composer-goal\.is-pursuing/)
  })

  it('queued inbox rows can be edited or deleted with icons', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/core-chat/src/web/composer.tsx'), 'utf8')
    expect(composer).toContain('PencilSquareIcon')
    expect(composer).toContain('dropInboxItem')
    expect(composer).toContain('aria-label="编辑排队消息"')
    expect(composer).toContain('aria-label="删除排队消息"')
    expect(css).toMatch(/\.composer-inbox-btn\s*\{[^}]*width:\s*24px/s)
  })

  it('puts the session mascot after the header name, with the dock session picker', () => {
    const approvals = readFileSync(resolve(root, 'packages/core-chat/src/web/approvals.tsx'), 'utf8')
    const title = readFileSync(resolve(root, 'packages/web-app-shell/src/web/chat-session-title.tsx'), 'utf8')
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const shell = readFileSync(resolve(root, 'packages/web-app-shell/src/web/index.tsx'), 'utf8')
    const overlayWin = readFileSync(resolve(root, 'packages/web-app-shell/src/web/overlay-window.tsx'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/core-chat/src/web/composer.tsx'), 'utf8')
    expect(title).not.toContain('BrandCornerMascot')
    expect(title).toContain('chat-session-title-pop')
    expect(approvals).toContain('BrandCornerMascot')
    expect(approvals).toContain('busy={sessionBusy}')
    expect(approvals).toMatch(/renderSlot\('header-tools'\)[\s\S]*BrandCornerMascot/)
    expect(approvals).toContain('variant="popover"')
    expect(composer).not.toContain('CaretMascot')
    expect(composer).not.toContain('caret-mascot')
    expect(css).toMatch(/\.chat-dock-toolbar \.brand-corner-cluster\s*\{[^}]*position:\s*relative/s)
    expect(approvals).toMatch(/chat-overlay-thread-toggle[\s\S]*SessionProjectPanel/)
    expect(approvals).not.toContain('dock-session-mascot')
    expect(approvals).not.toContain('BrandAgentMenu')
    expect(approvals).not.toContain('setSessionPickerOpen')
    expect(shell).not.toMatch(/hit\.closest\('\.dock-agent-stack'\)/)
    expect(shell).toContain('OverlayChatWindow')
    expect(overlayWin).toContain('ChatPane')
    expect(overlayWin).toContain('chat-overlay-head')
    expect(overlayWin).not.toContain('chat-overlay-peek')
    expect(overlayWin).not.toContain('查看对话')
    expect(overlayWin).not.toContain('startDrag')
    expect(overlayWin).not.toContain('chat-overlay-drag')
    expect(overlayWin).toContain('data-biu-ignore')
    expect(overlayWin).toContain("key: 'se'")
    expect(overlayWin).toContain('chat-overlay-resize-')
    expect(overlayWin).not.toContain('chat-overlay-layout-toggle')
    expect(overlayWin).not.toContain('layoutTools')
    expect(css).toMatch(/\.chat-overlay-panel \{/)
    expect(css).toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*var\(--dsw-sidebar\)/s)
    expect(css).toMatch(/\.chat-overlay-panel\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*backdrop-filter:\s*blur/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*transparent/s)
    // 浮窗要落在侧栏色上，和画布底色区分开，别退回成和正文一样的底。
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*var\(--dsw-bg\)/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1\)/s)
    expect(css).toMatch(/\.chat-overlay-head\s*\{[^}]*z-index:\s*30/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-overlay-thread\s*\{[^}]*padding-block:\s*0/s)
    expect(css).not.toMatch(/\.chat-overlay-panel \.chat-overlay-thread\s*\{[^}]*padding-bottom:\s*5\.5rem/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-stage\s*\{[^}]*padding-top:\s*0/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-stage\s*\{[^}]*padding-bottom:\s*18rem/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*position:\s*absolute/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*bottom:\s*20px/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*height:\s*auto/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*padding:\s*0 16px/s)
    expect(css).toMatch(/\.composer-pill\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).toMatch(/\.composer-pill\s*\{[^}]*box-shadow:\s*none/s)
    expect(css).toMatch(/\.chat-overlay-panel \.composer-pill\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).toMatch(/\.chat-overlay-panel \.chat-pane \.chat-composer-dock\s*\{[^}]*background:\s*transparent/s)
    expect(css).toMatch(/\.chat-pane \.chat-composer-dock\s*\{[^}]*z-index:\s*10/s)
    expect(css).toMatch(/\.chat-pane-embed\s*\{[^}]*background:\s*var\(--dsw-bg\)/s)
    expect(css).not.toMatch(/\.chat-overlay-panel\.is-autohide/)
    expect(css).toMatch(/\.composer-pill/)
    expect(css).toMatch(/\.composer-pill\s*\{[^}]*background:\s*var\(--dsw-sidebar\)/s)
    expect(css).not.toMatch(/\.composer-pill\s*\{[^}]*backdrop-filter:\s*blur/s)
    expect(css).not.toMatch(/\.composer-pill\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1\)/s)
  })

  it('squares the composer when pick chips are present', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const composer = readFileSync(resolve(root, 'packages/core-chat/src/web/composer.tsx'), 'utf8')
    expect(composer).toMatch(/has-chips/)
    expect(css).toMatch(/\.composer-pill\.has-chips[\s\S]*border-radius:\s*var\(--dsw-radius-bubble\)/)
  })

  it('uses facet tones for pick chips and the clear-context control, not the plus', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const chip = readFileSync(resolve(root, 'packages/core-pick/src/web/chip.tsx'), 'utf8')
    const node = readFileSync(resolve(root, 'packages/core-chat/src/web/composer-pick-node.tsx'), 'utf8')
    const approvals = readFileSync(resolve(root, 'packages/core-chat/src/web/approvals.tsx'), 'utf8')
    expect(css).toMatch(/\.project-chip\.project-chip-clear-ctx:hover:not\(:disabled\)\s*\{[^}]*color:\s*#d9730d/s)
    expect(css).toMatch(/\.project-chip-hist-bar\s*\{[^}]*color-mix\(in srgb, var\(--biu-tag, #d9730d\) 22%, transparent\)/s)
    expect(css).toMatch(/\.composer-plus\s*\{[^}]*background:\s*var\(--dsw-bubble\)/s)
    // 加号 / 模型入口 / 芯片 / dock 按钮与项目文件夹同一套底和字色。
    expect(css).toMatch(/\.composer-plus\s*\{[^}]*color:\s*var\(--dsw-icon-active\)/s)
    expect(css).toMatch(/\.composer-model-trigger\s*\{[^}]*color:\s*var\(--dsw-icon-active\)/s)
    expect(css).toMatch(/\.project-chip\s*\{[^}]*color:\s*var\(--dsw-icon-active\)/s)
    expect(css).toMatch(/\.project-chip\s*\{[^}]*background:\s*var\(--dsw-bubble\)/s)
    expect(css).toMatch(/\.dock-icon-btn\s*\{[^}]*color:\s*var\(--dsw-icon-active\)/s)
    expect(css).toMatch(/\.dock-icon-btn\s*\{[^}]*background:\s*var\(--dsw-bubble\)/s)
    expect(css).toMatch(/\.dock-icon-btn\.is-active\s*\{[^}]*background:\s*var\(--dsw-pick-fill\)/s)
    expect(approvals).toMatch(/<BrandCornerMascot[\s\S]*size=\{28\}/)
    expect(approvals).toMatch(/project-chip-clear-ctx/)
    expect(approvals).toMatch(/project-chip-hist-bar/)
    expect(approvals).toMatch(/histRatio \* 100/)
    expect(css).toMatch(/\.project-chip\s*\{[^}]*border:\s*1px solid var\(--dsw-border\)/s)
    expect(css).not.toMatch(/\.project-chip\.project-chip-clear-ctx\s*\{[^}]*border:\s*1px solid #d9730d/s)
    // 选取开关只靠文字色表达状态，不要额外描一圈强调色的边。
    expect(css).not.toMatch(/\.project-chip\.project-chip-pick-toggle\s*\{[^}]*border:\s*1px solid var\(--dsw-pick\)/s)
    expect(css).toMatch(
      /\.project-chip\.project-chip-follow-toggle\.is-active:hover:not\(:disabled\)\s*\{[^}]*border-color:\s*var\(--dsw-border\)/s,
    )
    expect(css).toMatch(/\.project-chip\.project-chip-pick-toggle:hover:not\(:disabled\)/)
    expect(css).toMatch(/\.project-chip\.project-chip-pick-toggle\.is-active[\s\S]*?color:\s*#5b9fd6/)
    expect(css).toMatch(/\.project-chip\.project-chip-follow-toggle:hover:not\(:disabled\)/)
    expect(css).toMatch(/\.project-chip\.project-chip-follow-toggle\.is-active[\s\S]*?color:\s*#5b9fd6/)
    expect(css).toMatch(/\[data-dock-tip-at='ne'\]::after/)
    expect(approvals).toMatch(/data-dock-tip-at="ne"/)
    expect(approvals).not.toContain('待确认工具 · 先处理后再发')
    expect(approvals).toContain('dock-approval-mark')
    expect(approvals).toMatch(/data-dock-tip="待确认"/)
    expect(approvals).toContain('dock-approval-card-actions')
    expect(approvals).toContain('dock-approval-card-head')
    expect(css).toMatch(/\.dock-approval-card\s*\{[^}]*min-height:\s*148px/s)
    expect(css).toMatch(/\.dock-approval-card-actions\s*\{[^}]*position:\s*absolute/s)
    expect(css).toMatch(/\.dock-approval-card-actions\s*\{[^}]*right:\s*12px/s)
    expect(css).toMatch(/\.dock-approval-card-actions\s*\{[^}]*bottom:\s*8px/s)
    expect(css).toMatch(/\.composer-tool-chip\.is-pick,\s*\n\.user-pick-chip\s*\{[^}]*--biu-tag/s)
    expect(chip).toMatch(/pickKindTone/)
    expect(chip).toMatch(/tagTone\(canonicalPickKind\(kind\)\)/)
    expect(chip).toMatch(/onRemove/)
    expect(chip).toMatch(/biu-tag-x/)
    expect(node).toMatch(/<PickChip pick=/)
    expect(node).toMatch(/onRemove=\{remove\}/)
  })

  it('defines the chrome palette tokens and derives the pick highlight from them', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    // 只断言 token 存在并有值，具体色值由主题决定，锁死了换主题就整片变红。
    expect(css).toMatch(/--dsw-bg:\s*[^;]+;/)
    expect(css).toMatch(/--dsw-placeholder:\s*[^;]+;/)
    expect(css).toMatch(/::placeholder\s*\{[^}]*color:\s*var\(--dsw-placeholder\)/)
    expect(css).toMatch(/--dsw-sidebar:\s*[^;]+;/)
    expect(css).toMatch(/--dsw-hover:\s*[^;]+;/)
    expect(css).toMatch(/--dsw-sidebar-fg:\s*[^;]+;/)
    expect(css).toMatch(/--dsw-sidebar-fg-active:\s*[^;]+;/)
    expect(css).toMatch(/--dsw-pick:\s*[^;]+;/)
    // 选取的填充/描边必须是从主色 color-mix 出来的半透明派生值，不能各写一个独立色。
    expect(css).toMatch(/--dsw-pick-fill:\s*color-mix\(in srgb,[^;]+\d+%, transparent\);/)
    expect(css).toMatch(/--dsw-pick-stroke:\s*color-mix\(in srgb,[^;]+\d+%, transparent\);/)
    expect(css).toMatch(/\.pick-overlay-box[\s\S]*background:\s*var\(--dsw-pick-fill\)/)
    expect(css).toMatch(/\.pick-overlay-marquee[\s\S]*background:\s*var\(--dsw-pick-fill\)/)
  })

  it('uses facet orange fill on clear-context only when there is history', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    const approvals = readFileSync(resolve(root, 'packages/core-chat/src/web/approvals.tsx'), 'utf8')
    expect(css).toMatch(/\.project-chip-hist-bar\s*\{[^}]*color-mix\(in srgb, var\(--biu-tag, #d9730d\) 22%, transparent\)/s)
    expect(approvals).toMatch(/project-chip-hist-bar/)
    expect(css).toMatch(/\.chat-pane\s*\{[^}]*--dsw-ok:\s*#448361/s)
    expect(css).toMatch(/\.chat-pane\s*\{[^}]*--dsw-danger:\s*#c4554d/s)
    expect(css).toMatch(/\.tool-call-status\.is-ok\s*\{[^}]*color:\s*#448361/s)
    expect(css).not.toMatch(/\.tool-call-status\.is-ok\s*\{[^}]*color-mix\(in srgb, #448361 22%, transparent\)/s)
    expect(css).toMatch(/\.tool-call-status\.is-fail\s*\{[^}]*color:\s*#c4554d/s)
    expect(css).not.toMatch(/\.tool-call-status\.is-fail\s*\{[^}]*color-mix\(in srgb, #c4554d 22%, transparent\)/s)
    expect(css).toMatch(/\.tool-call-chevron\.is-ok\s*\{[^}]*color:\s*#448361/s)
    expect(css).toMatch(/\.tool-call-chevron\.is-fail\s*\{[^}]*color:\s*#c4554d/s)
    expect(css).toMatch(/\.tool-call-head\.is-open\.is-ok::before[\s\S]*#448361 22%/)
    expect(css).toMatch(/\.tool-call-head\.is-open\.is-fail::before[\s\S]*#c4554d 22%/)
    expect(css).toMatch(/\.tool-call-inspect\s*\{[^}]*opacity:\s*0/s)
    expect(css).toMatch(/\.tool-call-head:hover \.tool-call-inspect/s)
    expect(css).toMatch(/\.traj-usage-ring\.is-cache\s*\{[^}]*color:\s*#448361/s)
    expect(css).toMatch(/\.traj-usage-ring\.is-hist\s*\{[^}]*color:\s*#d9730d/s)
    expect(css).toMatch(/:root \{[^}]*--dsw-usage-track-cache: color-mix\(in srgb, #448361 22%, #ffffff\)/)
    expect(css).toMatch(/:root \{[^}]*--dsw-usage-track-hist: color-mix\(in srgb, #d9730d 22%, #ffffff\)/)
    expect(css).toMatch(/\.chat-assistant-action\s*\{[^}]*color:\s*var\(--dsw-icon\)/s)
    expect(css).toMatch(/\.chat-reply-meta-icon\s*\{[^}]*color:\s*var\(--dsw-icon\)/s)
    expect(css).toMatch(/html\.dark \.chat-pane,\s*\nhtml\.dark \.chat-overlay-panel\s*\{[^}]*--dsw-icon:\s*#91918e/s)
    const usage = readFileSync(resolve(root, 'packages/core-chat/src/web/usage-inline.tsx'), 'utf8')
    expect(usage).toMatch(/var\(--dsw-usage-track-cache\)/)
    expect(usage).toMatch(/var\(--dsw-usage-track-hist\)/)
    expect(usage).toMatch(/TAG_TONE_GREEN/)
    expect(usage).toMatch(/TAG_TONE_ORANGE/)
    expect(usage).toMatch(/stroke="currentColor"/)
    expect(approvals).toContain('上下文占输入文字')
    expect(approvals).not.toMatch(/清空上下文 · 历史/)
    expect(approvals).not.toMatch(/backgroundColor/)
    expect(approvals).not.toMatch(/<ChatLiveMetrics/)
    expect(approvals).toMatch(/typeof props.renderSlot === 'function'/)
    expect(approvals).toMatch(/aria-label="清空上下文"[\s\S]*renderSlot\('header-tools'\)/)
  })

  it('paints inspector trajectory and usage on the same sidebar token as the left rail', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    expect(css).toMatch(/\.traj-root\s*\{[^}]*background:\s*var\(--dsw-sidebar\)/s)
    expect(css).toMatch(/\[data-testid='session-inspector'\] \.usage-panel\s*\{[^}]*background:\s*var\(--dsw-bg\)/s)
    expect(css).toMatch(/\.session-inspector\s*\{[^}]*background:\s*var\(--dsw-bg\)/s)
    expect(css).toMatch(/\.session-inspector \.app-side-bar-head\s*\{[^}]*background:\s*var\(--dsw-bg\)/s)
    expect(css).toMatch(/\[data-testid='session-inspector'\] \.traj-root[\s\S]*background:\s*var\(--dsw-sidebar\)/)
  })

  it('keeps pick chips from inheriting the composer line-height', () => {
    const css = readFileSync(resolve(root, 'web/style.css'), 'utf8')
    expect(css).toMatch(/\.composer-inline-chip\s*\{[^}]*align-items:\s*center/s)
    expect(css).toMatch(/\.composer-inline-chip\s*\{[^}]*vertical-align:\s*middle/s)
    expect(css).toMatch(/\.composer-inline-chip\s*\{[^}]*line-height:\s*1/s)
    expect(css).toMatch(/\.composer-tool-chip\.is-pick,\s*\n\.user-pick-chip\s*\{[^}]*line-height:\s*20px/s)
    expect(css).toMatch(/\.composer-tool-chip\.is-pick>span\.pick-chip-lines,\s*\n\.user-pick-chip>span\.pick-chip-lines\s*\{[^}]*flex:\s*none/s)
    expect(css).toMatch(/\.composer-tool-chip\.is-pick>span\.pick-chip-lines,\s*\n\.user-pick-chip>span\.pick-chip-lines\s*\{[^}]*min-width:\s*max-content/s)
    expect(css).toMatch(/\.pick-kind-icon\s*\{[^}]*display:\s*block/s)
    expect(css).toMatch(
      /\.composer-pill\.has-chips \.composer-tiptap p,\s*\n\.composer-tiptap\.is-readonly p \{\s*line-height:\s*1\.45/,
    )
  })

  it('uses Tiptap for inline pick chips in the composer', () => {
    const composer = readFileSync(resolve(root, 'packages/core-chat/src/web/composer.tsx'), 'utf8')
    const kit = readFileSync(resolve(root, 'packages/core-chat/src/web/composer-kit.ts'), 'utf8')
    const node = readFileSync(resolve(root, 'packages/core-chat/src/web/composer-pick-node.tsx'), 'utf8')
    expect(composer).toMatch(/useEditor/)
    expect(composer).toMatch(/composerDocExtensions/)
    expect(composer).toMatch(/page-mention/)
    expect(kit).toMatch(/pageMention/)
    expect(composer).toMatch(/EditorContent/)
    expect(composer).toMatch(/insertPickChips/)
    expect(composer).toMatch(/stillMissing/)
    expect(composer).toMatch(/collectPickKeys\(editor\)/)
    expect(composer).toMatch(/takeDraft/)
    expect(composer).toMatch(/COMPOSER_PASTE_PICK_CHARS/)
    expect(composer).toMatch(/textPickFromPlain/)
    expect(composer).toMatch(/live\.current\.pick\?\.add\(ref\)/)
    expect(node).not.toMatch(/ReactNodeViewRenderer/)
    expect(node).toMatch(/queueMicrotask/)
  })
})
