import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'vitest'
import assert from 'node:assert/strict'

const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
const detail = readFileSync(resolve(import.meta.dirname, './record-detail.tsx'), 'utf8')

test('hydrating page-blocks prefers the route view over local 全部', () => {
  assert.match(browser, /pickViewForRoute\(listed, collectionPath, routeViewId\)/)
  assert.match(browser, /pickViewForRoute\(listed, collectionPath, routeViewId \?\? activeId/)
  assert.doesNotMatch(
    browser,
    /listed.find\(\(item\) => item.id === routeViewId\) \?\?\s*listed.find\(\(item\) => item.id === loadActiveViewId/,
  )
})

test('data sidebar brand sits left with a collapse control on the right', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  assert.match(sidebar, /app-side-bar-head-brand/)
  assert.match(sidebar, /SidebarBrandLockup/)
  assert.match(sidebar, /data-testid="sidebar-collapse"/)
  assert.doesNotMatch(sidebar, /SidebarBrandMascot/)
  assert.match(browser, /onCollapse=\{toggleViewsOpen\}/)
  assert.match(browser, /biu:toggle-shell-sidebar/)
  assert.match(sidebar, /shell-module-sidebar/)
})

test('user and system collection sections fold independently', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const fold = readFileSync(resolve(import.meta.dirname, '../../../public-ui/src/sidebar-fold.tsx'), 'utf8')
  assert.match(sidebar, /const \[userOpen, setUserOpen\] = useState\(true\)/)
  assert.match(sidebar, /const \[systemOpen, setSystemOpen\] = useState\(true\)/)
  assert.match(sidebar, /onClick=\{\(\) => setUserOpen\(\(prev\) => !prev\)\}/)
  assert.match(sidebar, /onClick=\{\(\) => setSystemOpen\(\(prev\) => !prev\)\}/)
  assert.match(sidebar, /<SidebarFold/)
  assert.match(fold, /function SidebarFold/)
  assert.match(fold, /className=\{\`sidebar-fold\$\{open \? ' is-open' : ''\}/)
  assert.doesNotMatch(sidebar, /sidebar-session-list min-w-0 \$\{open \? '' : 'hidden'\}/)
  assert.doesNotMatch(sidebar, /\{userOpen \?/)
  assert.doesNotMatch(sidebar, /\{systemOpen \?/)
  assert.doesNotMatch(sidebar, /\{favOpen \?/)
})

test('grouped views nest a foldable group layer in the sidebar', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.match(sidebar, /groupRecords\(state\.items, state\.schema, view\.groupBy\)/)
  assert.match(sidebar, /data-testid="sidebar-view-group"/)
  assert.match(sidebar, /fsdb-view-preview-records/)
  assert.match(css, /\.fsdb-view-preview-records \.chat-session-row > \.chat-session-row-main/)
})

test('table and view rows only expand from the fold column', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  assert.match(css, /\.sidebar-fold\s*\{[^}]*grid-template-rows:\s*0fr/s)
  assert.match(css, /\.sidebar-fold\.is-open\s*\{[^}]*grid-template-rows:\s*1fr/)
  assert.match(css, /\.sidebar-fold\.is-animating\s*\{[^}]*transition:\s*grid-template-rows/)
  assert.doesNotMatch(css, /\.sidebar-fold\s*\{[^}]*transition:\s*grid-template-rows/s)
  assert.match(sidebar, /const listed = path === collectionPath \? views : loadViews\(path\)/)
  assert.match(sidebar, /viewsForRegisteredCollection\(path, tables, listed\)/)
  assert.doesNotMatch(sidebar, /catalog: true/)
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.doesNotMatch(page, /opts\?\.catalog/)
  assert.match(page, /go\(\{ collection: path, viewId: viewId \?\? builtinAllViewId\(path\) \}\)/)
  assert.doesNotMatch(page, /recordsPath=\{recordsPath\}/)
  assert.doesNotMatch(page, /isCollectionHub/)
  assert.doesNotMatch(page, /go\(\{ collection: path, viewId: viewId \?\? defaultViewId\(path\) \}\)/)
  assert.match(sidebar, /setUserOpen/)
  assert.match(sidebar, /setSystemOpen/)
  assert.doesNotMatch(sidebar, /onClick=\{\(\) => setDataOpen/)
  assert.doesNotMatch(sidebar, /useState<Record<string, boolean>>\(\(\) => \(\{ \[table\.path\]: true \}\)\)/)
  assert.doesNotMatch(sidebar, /setOpenTables\(\(prev\) => \(\{ \.\.\.prev, \[path\]: true \}\)\)/)
  assert.match(sidebar, /用户数据/)
  assert.match(sidebar, /系统数据/)
  assert.match(sidebar, /data-testid="sidebar-user-collections"/)
  assert.match(sidebar, /data-testid="sidebar-system-collections"/)
  assert.match(sidebar, /className="flex min-w-0 flex-col gap-px" data-testid="sidebar-user-collections"/)
  assert.match(sidebar, /className="flex min-w-0 flex-col gap-px" data-testid="sidebar-system-collections"/)
  assert.match(sidebar, /className="flex min-w-0 flex-col gap-px" data-collection-kind/)
  assert.match(sidebar, /className="sidebar-group-head"/)
  assert.doesNotMatch(sidebar, /sidebar-group-head mb-0\.5/)
  assert.match(sidebar, /data-collection-kind/)
  assert.match(sidebar, /isSystemCollection/)
  assert.match(sidebar, /className="sidebar-add"/)
  assert.match(sidebar, /onAddView\(table\.path\)/)
  assert.match(css, /\.sidebar-group-fold:hover \.sidebar-group-fold-chevron/)
  assert.doesNotMatch(css, /\.chat-session-row:hover \.sidebar-group-fold-chevron/)
})

test('sidebar records paint detail immediately without reloading the view', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.match(browser, /setOpenDetailId\(recordId\)/)
  assert.match(browser, /if \(row\) setDetailRow\(row\)/)
  assert.match(browser, /queueMicrotask\(\(\) => onOpenRecord\?\.\(recordId, view\.id, path\)\)/)
  assert.doesNotMatch(browser, /flushSync/)
  assert.match(browser, /if \(path === collectionPath\) \{\s*applyView\(view\)/)
  assert.doesNotMatch(browser, /onOpenRecord=\{\(path, view, recordId\) => \{\s*selectView/)
  assert.match(page, /viewId: viewId \?\? viewFromRoute/)
  assert.match(page, /parsed\.kind === 'collection-view' \|\| parsed\.kind === 'record'\s*\n\s*\? parsed\.viewId/)
  assert.match(browser, /!detailId \?/)
  assert.match(sidebar, /onOpenRecord\?\.\(row\.id, row\)/)
  assert.match(sidebar, /event.stopPropagation\(\)/)
  const emoji = readFileSync(resolve(import.meta.dirname, '../../../public-ui/src/emoji-board.tsx'), 'utf8')
  assert.match(emoji, /function RecordEmojiBoard/)
  assert.match(emoji, /className="fsdb-emoji-picker is-fixed"/)
  assert.doesNotMatch(emoji, /fsdb-emoji-picker-input/)
  assert.doesNotMatch(emoji, />恢复默认</)
  assert.match(emoji, /aria-label="恢复默认"/)
  assert.match(sidebar, /fsdb-record-emoji/)
  assert.match(css, /\.fsdb-record-emoji \{[^}]*display:\s*inline-flex/s)
  assert.match(css, /\.fsdb-record-emoji \{[^}]*width:\s*16px/s)
  assert.match(css, /\.fsdb-record-emoji \{[^}]*height:\s*16px/s)
  assert.match(css, /\.fsdb-record-emoji \{[^}]*align-items:\s*center/s)
  assert.match(css, /\.fsdb-record-emoji \{[^}]*justify-content:\s*center/s)
  assert.match(css, /\.fsdb-emoji-picker \{[^}]*border-radius:\s*12px/s)
  assert.match(css, /\.fsdb-emoji-picker \{[^}]*background:\s*#1c1c1c/s)
  assert.match(css, /\.fsdb-emoji-picker-presets \{[^}]*grid-template-columns:\s*repeat\(8/)
  assert.match(detail, /key === 'emoji'/)
  assert.match(detail, /<RecordEmojiBoard/)
})

test('pages and tasks sidebar records nest by parentId; other tables stay flat', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  const css = readFileSync(resolve(import.meta.dirname, '../../../../web/style.css'), 'utf8')
  const path = readFileSync(resolve(import.meta.dirname, './database-path.ts'), 'utf8')
  assert.match(path, /PAGES_COLLECTION_PATH = '\/pages'/)
  assert.match(path, /TASKS_COLLECTION_PATH = '\/tasks'/)
  assert.match(path, /function isRecordTreeCollection/)
  assert.match(sidebar, /isRecordTreeCollection\(path\)/)
  assert.match(sidebar, /treeChildren\(scope, parentKey, parentId\)/)
  assert.match(sidebar, /title=\{\`\$\{kidCount\} 个子记录\`\}/)
  assert.match(sidebar, /在 \$\{label\} 下添加子记录/)
  assert.match(sidebar, /toggleStarredRecord/)
  assert.match(sidebar, /records: \[\{ \[parentKey\]: row\.id \}\]/)
  assert.match(sidebar, /if \(!nested\)/)
  assert.match(css, /\.chat-session-row:hover \.sidebar-add/)
  assert.match(css, /\.fsdb-record-kids/)
  assert.doesNotMatch(css, /\.chat-session-row:hover \.sidebar-group-fold-chevron/)
})

test('starred pages and tasks also list in the sidebar favorites section', () => {
  const sidebar = readFileSync(resolve(import.meta.dirname, './data-sidebar.tsx'), 'utf8')
  assert.match(sidebar, /const favCount = starredRows\.length \+ starredRecordRows\.length/)
  assert.match(sidebar, /\{favCount \?/)
  assert.match(sidebar, /starredRecordRows\.map/)
  assert.match(sidebar, /star-record:\$\{table\.path\}:\$\{item\.recordId\}/)
  assert.match(sidebar, /starredRecordLabel\(item\)/)
  assert.match(sidebar, /rootId=\{item\.recordId\}/)
  assert.match(sidebar, /isRecordTreeCollection\(table\.path\)/)
  assert.match(sidebar, /title=\{expanded \? '收起子记录' : '展开子记录'\}/)
  assert.doesNotMatch(sidebar, /\{starredRows\.length \?/)
})

test('table title opens record from the title-side button', () => {
  assert.match(browser, /data-testid="record-title-open"/)
  assert.match(browser, /data-testid="record-title-split"/)
  assert.match(browser, /showRecordInInspector\(collectionPath, row.id\)/)
  assert.match(browser, /className="tasks-icon-btn tasks-title-open"/)
  assert.match(browser, /tasks-title-aside/)
  assert.match(browser, /tasks-tree-count/)
  assert.match(browser, /kidCount/)
  assert.match(browser, /tasks-tree-toggle is-empty/)
  assert.match(browser, /hasTreeLinks\(items, parentKey\)/)
  assert.match(browser, /const treeOn = treeable && showTree/)
  assert.match(browser, /const tree = openDetail && treeOn/)
  assert.match(browser, /openRow\(row\)/)
  assert.doesNotMatch(browser, /focusInspectorIfOpen/)
  assert.match(browser, /chrome\?\.openRow/)
  assert.doesNotMatch(browser, /catalogRowOpenTarget/)
  assert.doesNotMatch(browser, /tagRowOpenTarget/)
  assert.doesNotMatch(browser, /stampRowOpenTarget/)
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.match(page, /viewsChrome/)
  assert.match(page, /pageBlocksChrome/)
  assert.doesNotMatch(page, /openRegisteredRow/)
  assert.doesNotMatch(page, /onOpenRow=\{/)
  assert.doesNotMatch(page, /addSchemaTagField/)
  const nav = readFileSync(resolve(import.meta.dirname, './collection-nav.ts'), 'utf8')
  assert.match(nav, /listViews/)
  assert.doesNotMatch(nav, /catalogRowOpenTarget/)
  assert.doesNotMatch(nav, /tagRowOpenTarget/)
  assert.doesNotMatch(nav, /stampRowOpenTarget/)
  assert.doesNotMatch(browser, /onAddField/)
  assert.doesNotMatch(browser, /<AddProperty/)
  assert.match(browser, /const lockedKind = String\(catalogLocks.blockKind/)
  assert.doesNotMatch(browser, /recordPick\(row\)\} onClick=\{\(\) => setDetailId\(row\.id\)\}/)
})

test('title cell row tools skip the overflow action menu', () => {
  assert.match(browser, /const Actions = chrome\?\.Actions/)
  assert.match(browser, /placedActions\(schema, place\)/)
  assert.match(browser, /<Actions actions=\{placed\} record=\{row\}/)
  assert.match(browser, /toolbar=\{<RecordActions row=\{selected\} place="detail" \/>\}/)
  assert.match(browser, /onDelete=\{canDelete \? \(\) => setDlg\(\{ kind: 'delete-record', row: selected \}\) : undefined\}/)
  assert.doesNotMatch(browser, /selected \? <RecordActions row=\{selected\} place="detail" \/> : null/)
  const detail = readFileSync(resolve(import.meta.dirname, './record-detail.tsx'), 'utf8')
  assert.match(detail, /toolbar/)
  assert.doesNotMatch(detail, /role="main" aria-label="记录详情">\s*\{toolbar\}/)
  assert.doesNotMatch(browser, /fsdb-detail-actionbar/)
  assert.match(detail, /data-testid="fsdb-detail-delete"/)
  assert.match(detail, /删除页面/)
  assert.match(detail, /actions=\{toolbar\}/)
  const css = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')
  assert.match(css, /\.fsdb-detail-more-item\.is-danger\{/)
  assert.match(browser, /collectionPath === '\/plugins' \? ' is-plugins'/)
  assert.match(browser, /fsdb-detail-more-item/)
  assert.match(browser, /listedSelected/)
  assert.match(browser, /overlayListed/)
  assert.match(browser, /overlayListed\(detailRow, listedSelected, listColumns\)/)
  assert.match(browser, /overlayListed\(prev, hit, listColumns\)/)
  assert.match(browser, /previewActionRecord/)
  assert.match(browser, /actingRef/)
})

test('deletable tables can pick rows and bulk-act over the table header', () => {
  assert.match(browser, /data-testid="fsdb-bulk-delete"/)
  assert.doesNotMatch(browser, /data-testid="fsdb-bulk-edit"/)
  assert.doesNotMatch(browser, /编辑属性/)
  assert.match(browser, /data-testid="fsdb-bulk-export"/)
  assert.match(browser, /data-testid="fsdb-bulk-facet"/)
  assert.match(browser, /data-testid="fsdb-bulk-facet"[\s\S]*合集/)
  assert.doesNotMatch(browser, /打合集/)
  assert.match(browser, /togglePicked\(list, header \? !some : !on\)/)
  assert.match(browser, /setPickedIds\(\[\]\)/)
  assert.match(browser, /data-testid="fsdb-bulk-more"/)
  assert.match(browser, /className="tasks-table-wrap"[\s\S]*data-testid="fsdb-bulk-bar"/)
  const toolbarRight = browser.slice(browser.indexOf('tasks-toolbar-right'), browser.indexOf('className="tasks-table-wrap"'))
  assert.doesNotMatch(toolbarRight, /fsdb-bulk-bar/)
  assert.match(browser, /\{pickedIds\.length\} 已选/)
  const bulkCss = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')
  assert.match(bulkCss, /\.fsdb-bulk\{[^}]*position:absolute/)
  assert.match(bulkCss, /\.fsdb-bulk\{[^}]*left:var\(--fsdb-check-gutter\)/)
  assert.match(bulkCss, /\.fsdb-bulk-count\{[^}]*color:var\(--dsw-pick/)
  assert.match(browser, /kind: 'delete-records'/)
  assert.match(browser, /kind: 'bulk-edit'/)
  assert.match(browser, /kind: 'bulk-facet'/)
  assert.match(browser, /exportPicked/)
  assert.match(browser, /zipMarkdownPack/)
  assert.match(browser, /for \(const id of ids\)/)
  assert.doesNotMatch(browser, /text\/csv/)
  assert.match(browser, /\.zip`/)
  assert.match(browser, /data-testid="fsdb-row-check"/)
  assert.match(browser, /className=\{\`fsdb-boolbtn fsdb-row-check\$\{marked \? ' is-on' : ''\}\`\}/)
  assert.match(browser, /<BoolBox/)
  const boolBox = readFileSync(resolve(import.meta.dirname, '../../../public-ui/src/bool-box.tsx'), 'utf8')
  assert.match(boolBox, /fsdb-boolbox/)
  assert.doesNotMatch(browser, /type="checkbox"/)
  assert.match(browser, /const canDelete = Boolean\(schema\?\.records\?\.delete\) && !subsetLocked/)
  assert.doesNotMatch(browser, /if \(!canDelete\) return null/)
  assert.match(browser, /if \(kind !== 'file'\)/)
  assert.match(browser, /<FieldValuePop/)
  assert.doesNotMatch(browser, /<FieldEditor/)
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  assert.match(cells, /if \(kind === 'select' \|\| kind === 'multi-select'\)/)
  assert.match(cells, /<TokenMultiSelect/)
  assert.match(cells, /multiple=\{kind === 'multi-select'\}/)
  assert.doesNotMatch(cells, /<CellSelect/)
  const schemaUi = readFileSync(resolve(import.meta.dirname, './schema-field.tsx'), 'utf8')
  assert.match(schemaUi, /person: '人物'/)
  assert.match(schemaUi, /ref: '引用'/)
  assert.match(schemaUi, /'multi-ref': '多引用'/)
  assert.match(schemaUi, /<CellMulti/)
  assert.doesNotMatch(schemaUi, /function TagPicker/)
  assert.match(schemaUi, /<FieldValuePop/)
  assert.match(schemaUi, /!parsed.tags.length/)
  assert.match(schemaUi, /type: 'facet'/)
  assert.doesNotMatch(schemaUi, /<FieldEditor/)
  assert.doesNotMatch(cells, /placeholder=\{fieldKey\}/)
  assert.doesNotMatch(cells, /YYYY-MM-DDTHH:mm/)
  assert.doesNotMatch(cells, /datetime-local/)
  assert.match(cells, /<CellDateTime/)
  assert.match(cells, /<PersonFace/)
  assert.match(cells, /<PersonPickPanel/)
  assert.match(cells, /RecordLinkChips/)
  assert.doesNotMatch(cells, /<RefFieldPop/)
  assert.doesNotMatch(cells, /<RecordPickPanel/)
  const people = readFileSync(resolve(import.meta.dirname, './person-cell.tsx'), 'utf8')
  assert.match(people, /asPersonList/)
  assert.match(people, /kind: 'user', name: '用户'/)
  assert.match(people, /kind: 'system', name: '系统'/)
  assert.match(people, /listCollection/)
  assert.match(people, /path: '\/sessions'/)
  assert.match(people, /resolveAgentName/)
  assert.doesNotMatch(people, /\/api\/sessions/)
  assert.match(cells, /<MediaField/)
  assert.doesNotMatch(cells, /placeholder=\{kind === 'image'/)
  const media = readFileSync(resolve(import.meta.dirname, './cell-media.tsx'), 'utf8')
  assert.doesNotMatch(media, /或填写链接/)
  assert.match(media, /kind === 'url'/)
  assert.match(media, /type="file"/)
  assert.match(media, /inputRef\.current\?\.click\(\)/)
  assert.match(media, /item\.type\.startsWith\('image\/'\)/)
  assert.match(media, /function AttachmentFile/)
  assert.match(media, /ArrowDownTrayIcon/)
  assert.match(media, /ArrowTopRightOnSquareIcon/)
  assert.match(media, /target="_blank"/)
  assert.match(media, /noopener noreferrer/)
  assert.match(cells, /kind === 'url'/)
  assert.match(cells, /<UrlHref href=\{href\} \/>/)
  assert.match(media, /download=\{file\.name\}/)
  assert.match(media, /commitAttachments/)
  assert.match(media, /fsdb-media-drop/)
  assert.match(media, /onDrop/)
  assert.match(media, /is-files/)
  assert.doesNotMatch(media, /粘贴或选择图片/)
  assert.doesNotMatch(media, /PhotoIcon/)
  assert.match(media, /ArrowUpTrayIcon/)
  assert.match(media, /collectClipboardFiles/)
  assert.match(media, /\/api\/db\/file/)
  assert.doesNotMatch(media, /这张表还没有附件存储/)
  assert.doesNotMatch(media, /fileToDataUrl/)
  assert.match(media, /multiple=\{kind === 'image' \|\| kind === 'attachment'\}/)
  assert.match(browser, /fsdb-file-tools/)
  assert.match(media, /file\.name/)
  assert.match(media, /file\.lastModified/)
  assert.match(media, /imagesRef\.current/)
  assert.match(media, /document\.addEventListener\('paste', onPaste, true\)/)
  assert.match(browser, /<FieldValuePop/)
  assert.match(browser, /onSubmit=\{\(next\) => writeCellValue\(row, key, field, next\)\}/)
  assert.match(browser, /const Custom = chrome\?\.cells\?\.\[key\][\s\S]*if \(kind !== 'file'\)/)
  assert.match(browser, /key && field\?\.writable \?/)
  assert.match(browser, /cellUsesPop/)
  assert.match(browser, /CELL_POP_DRAG_PX/)
  assert.match(browser, /start\?\.dragged/)
  assert.match(browser, /onClick=\{\(event\) => \{[\s\S]*?setCellPop\(cellUsesPop/)
  assert.match(browser, /cellPopPtrRef\.current = \{ x: event\.clientX, y: event\.clientY, dragged: false \}/)
  assert.match(browser, /if \(surface === 'table'\)/)
  assert.match(browser, /<CellPopDraft/)
  const popDraft = readFileSync(resolve(import.meta.dirname, './cell-pop-draft.tsx'), 'utf8')
  assert.match(popDraft, /loadFacets, persistFacets, slugFacetId, subscribeFacets/)
  assert.doesNotMatch(popDraft, /提交/)
  assert.doesNotMatch(popDraft, /取消/)
  assert.match(popDraft, /fsdb-cell-pop-tags/)
  assert.match(popDraft, /fsdb-cell-pop-text/)
  assert.match(popDraft, /fsdb-cell-pop-url/)
  assert.match(popDraft, /rawRef\.current = next\.trim\(\)/)
  assert.doesNotMatch(popDraft, /kind === 'datetime' \|\| kind === 'image' \|\| kind === 'attachment' \|\| kind === 'url'/)
  assert.match(popDraft, /kind === 'facet'/)
  assert.match(popDraft, /kind === 'person'/)
  assert.match(popDraft, /PersonPickPanel/)
  assert.match(popDraft, /isRecordLinkField/)
  assert.match(popDraft, /RecordPickPanel/)
  assert.match(popDraft, /onJump=\{onClose\}/)
  const refs = readFileSync(resolve(import.meta.dirname, './record-link-cell.tsx'), 'utf8')
  assert.match(refs, /fsdb-ref-pick/)
  assert.match(refs, /showRecordInInspector/)
  assert.match(refs, /fsdb-ref-jump/)
  assert.match(refs, /\/api\/db\/read/)
  assert.doesNotMatch(refs, /fsdb-ref-id/)
  assert.doesNotMatch(refs, /function RefFieldPop/)
  assert.doesNotMatch(refs, /<CellPop/)
  assert.doesNotMatch(refs, /TagChip/)
  const valuePop = readFileSync(resolve(import.meta.dirname, './field-value-pop.tsx'), 'utf8')
  assert.match(valuePop, /function FieldValuePop/)
  assert.match(valuePop, /<CellPop/)
  assert.match(valuePop, /<CellPopDraft/)
  assert.match(valuePop, /fsdb-pop-host/)
  assert.match(valuePop, /fieldHasValue/)
  assert.match(valuePop, /fsdb-pop-empty/)
  assert.match(valuePop, />空</)
  assert.match(valuePop, /kind === 'datetime'/)
  assert.match(valuePop, /<CellDateTime/)
  assert.match(browser, /\.db-datetime, \.ant-picker/)
  assert.match(popDraft, /retagSchemaValue\(parsed, resolved\)/)
  assert.match(popDraft, /sameDraft\(next, initial\)/)
  assert.doesNotMatch(popDraft, /SchemaFieldEditor/)
  assert.doesNotMatch(browser, /if \(pop\) return <DefaultCell field=\{field\} value=\{row\[key\]\}/)
  const controls = readFileSync(resolve(import.meta.dirname, './controls.tsx'), 'utf8')
  assert.match(controls, /useEffect\(\(\) => \(\) => commit\(\), \[\]\)/)
  const pop = readFileSync(resolve(import.meta.dirname, './cell-pop.tsx'), 'utf8')
  assert.match(pop, /top: rect\.top/)
  assert.match(pop, /left: rect\.left/)
  assert.doesNotMatch(pop, /rect\.bottom \+ 4/)
  assert.match(pop, /kind !== 'action' && kind !== 'file' && kind !== 'boolean' && kind !== 'datetime'/)
  assert.match(browser, /kind === 'boolean'/)
  assert.match(browser, /<BoolCell on=\{on\} writable onToggle/)
  assert.match(browser, /renderCell\(row, key, field, 'table'\)/)
  assert.match(browser, /is-cell-on/)
  assert.match(browser, /is-cell-ro/)
  assert.match(browser, /cellFieldWritable/)
  assert.match(browser, /<CellPop/)
  assert.match(browser, /\.fsdb-thumb-btn, \.fsdb-thumb, \.ant-image/)
  assert.match(browser, /\.fsdb-ref-chip/)
  assert.doesNotMatch(browser, /skipBoolean/)
})

test('creating a record opens a new inspector pane instead of covering the view', () => {
  const createFn = browser.slice(browser.indexOf('async function createRecord'), browser.indexOf('async function executeDeleteRecord'))
  assert.match(createFn, /showRecordInInspector\(collectionPath, id\)/)
  assert.doesNotMatch(createFn, /setOpenDetailId/)
  assert.doesNotMatch(createFn, /onOpenRecord/)
})

test('create record sits at the right of the toolbar with a blue label', () => {
  assert.match(browser, /aria-label="排序"[\s\S]*aria-label="筛选"[\s\S]*aria-label="分组"/)
  assert.match(browser, /chrome\?\.Toolbar/)
  assert.match(browser, /className="fsdb-create-btn"/)
  assert.match(browser, /新建记录/)
  assert.match(browser, /<PlusIcon[\s\S]*新建/)
  assert.doesNotMatch(
    browser,
    /className="tasks-toolbar-left"[\s\S]*?aria-label="新建记录"[\s\S]*?className="tasks-toolbar-right"/,
  )
  const css = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')
  assert.match(css, /\.fsdb-create-btn\{[^}]*border-radius:4px/)
  assert.match(css, /\.fsdb-create-btn\{[^}]*background:var\(--dsw-pick/)
  assert.match(css, /\.fsdb-boolbox\.is-on\{[^}]*background:var\(--dsw-pick/)
  assert.match(css, /\.fsdb-row-check\{[^}]*opacity:0/)
  assert.match(css, /\.fsdb-row-check\{[^}]*pointer-events:auto/)
  assert.match(css, /\.fsdb-row-check\{[^}]*transition:none/)
  assert.match(css, /\.fsdb-check-slot\.is-hover \.fsdb-row-check/)
  assert.match(css, /\.fsdb-check-slot:hover \.fsdb-row-check/)
  assert.match(browser, /paintCheckHover/)
  assert.match(browser, /CSS as DndCSS/)
  assert.match(browser, /typeof CSS\.escape === 'function' \? CSS\.escape\(next\)/)
  assert.doesNotMatch(browser, /setCheckHover/)
  assert.match(browser, /data-check=\{slot\.kind === 'head' \? 'head' : slot\.id\}/)
  assert.match(css, /fsdb-check-rail/)
  assert.match(css, /\.fsdb-page \.fsdb-check-rail\{[^}]*width:var\(--fsdb-check-gutter\)/)
  assert.match(css, /\.fsdb-page \.fsdb-check-stack\{[^}]*transform:none/)
  assert.match(css, /\.fsdb-page \.tasks-table-wrap\{[^}]*overflow:auto/)
  assert.doesNotMatch(css, /overflow-clip-margin/)
  assert.doesNotMatch(css, /\.fsdb-page \.tasks-table-wrap\{[^}]*padding-left:var\(--fsdb-check-gutter\)/)
  assert.doesNotMatch(css, /translate\(calc\(-100% - 4px\),-50%\)/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot\{[^}]*width:auto/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot \.tasks-row-tools\{[^}]*position:static/)
  assert.match(css, /\.fsdb-page \.tasks-row-tools-slot \.tasks-row-tools\{[^}]*background:transparent/)
  assert.doesNotMatch(css, /tasks-row-tools-slot \.tasks-row-tools\{[^}]*linear-gradient/)
  assert.match(css, /\.fsdb-page \.tasks-table td:has\(\.fsdb-title-host:focus-within\) \.tasks-row-tools-slot/)
  assert.match(browser, /tasks-row-tools-slot/)
  assert.doesNotMatch(browser, /tasks-title-cell/)
  assert.doesNotMatch(css, /tasks-title-cell/)
  assert.doesNotMatch(css, /\.fsdb-row-check \.fsdb-boolbox/)
  assert.match(css, /\.tasks-table\{[^}]*border-collapse:separate/)
  assert.match(browser, /function tableBodyRows/)
  assert.match(browser, /markCellOn/)
  assert.doesNotMatch(browser, /<TableBodyRows/)
  assert.match(browser, /fsdb-check-rail/)
  assert.match(browser, /slot\.kind === 'head' \? <RowCheck ids=\{pickableIds\} \/> : null/)
  assert.match(browser, /slot\.kind === 'row' && slot\.id \? <RowCheck id=\{slot\.id\} \/> : null/)
  assert.doesNotMatch(browser, /col.key === titleColKey \? <RowCheck/)
  assert.doesNotMatch(browser, /fsdb-title-lead/)
  const titleFn = browser.slice(browser.indexOf('function RecordTitle'), browser.indexOf('function TableRecordIcon'))
  assert.match(titleFn, /<RecordOpenControls/)
  assert.match(titleFn, /<RecordRowTools/)
  assert.doesNotMatch(titleFn, /<RowCheck/)
  assert.match(css, /\.tasks-minicard-title\{[^}]*font-size:14px/)
  assert.match(css, /\.tasks-minicard-title\{[^}]*font-weight:600/)
  assert.doesNotMatch(css, /fsdb-row-check-cell/)
  assert.match(browser, /persistViewDisplay/)
  assert.match(browser, /withViewDisplay/)
  assert.doesNotMatch(browser, /if \(current\?\.builtin\) return/)
  assert.doesNotMatch(browser, /setColumnKeys\(defaultColumnKeys\(listed\.schema/)
  assert.match(browser, /flattenFacetColumns\(facetCatalog\)/)
  assert.match(browser, /facetColumnTitle\(col\)/)
  assert.match(browser, /function FacetColumnPackRow/)
  assert.match(browser, /function ColumnOrderMenu/)
  assert.match(browser, /columnKeys.length \? columnKeys : schemaDefaultKeys/)
  assert.match(browser, /onReorder=\{setVisibleColumns\}/)
  assert.match(browser, /\.\.\.hidden/)
  assert.match(browser, /data-fsdb-col-flyout/)
  assert.doesNotMatch(browser, /data-fsdb-col-flyout[\s\S]{0,80}tasks-sort-head/)
  assert.match(browser, /className=\{`fsdb-col-facet-dot/)
  const facetFlyout = browser.slice(browser.indexOf('function FacetColumnPackRow'), browser.indexOf('function recordsFingerprint'))
  assert.doesNotMatch(facetFlyout, /tasks-sort-head/)
  assert.match(browser, /<SchemaFieldEditor/)
  const schemaUi = readFileSync(resolve(import.meta.dirname, './schema-field.tsx'), 'utf8')
  assert.match(schemaUi, /retagSchemaValue\(liveRef.current, resolved\)/)
  assert.doesNotMatch(browser, /<SchemaFieldEditor[\s\S]{0,240}autoOpen/)
  assert.match(readFileSync(resolve(import.meta.dirname, './cell-pop-draft.tsx'), 'utf8'), /autoOpen/)
  assert.match(browser, /schemaTagTone\(flat\.packId\)/)
  assert.match(browser, /className=\{tone \? 'is-facet-col' : undefined\}/)
  assert.match(css, /\.tasks-table th\.is-facet-col\{[^}]*color:color-mix\(in srgb,var\(--biu-tag\) 8%,#fff\)/)
  assert.match(css, /\.tasks-table th\.is-facet-col\{[^}]*background:color-mix\(in srgb,var\(--biu-tag\) 22%,var\(--dsw-surface\)\)/)
  assert.match(css, /\.tasks-table\.is-wrap\{[^}]*white-space:normal/)
  assert.match(css, /\.tasks-table th,\.fsdb-page \.tasks-table\.is-wrap th\{[^}]*white-space:nowrap/)
  assert.match(css, /\.tasks-th\{[^}]*white-space:nowrap/)
})

test('filesystem list is table-only; extra modes come from registerView', () => {
  assert.doesNotMatch(browser, /function MiniCard/)
  assert.doesNotMatch(browser, /function QueueRow/)
  assert.doesNotMatch(browser, /mode === 'cards'/)
  assert.doesNotMatch(browser, /mode === 'queue'/)
  assert.doesNotMatch(browser, /mode === 'board'/)
  assert.match(browser, /function RecordRowTools/)
  assert.match(browser, /className="fsdb-title-host"/)
  assert.doesNotMatch(browser, /<th>操作<\/th>/)
  assert.match(browser, /aria-label="查看模式"/)
  assert.match(browser, /if \(customView\) return undefined/)
  assert.match(browser, /data-testid="fsdb-mode-plus"/)
  assert.match(browser, /askNewPresentation/)
  assert.doesNotMatch(browser, /extraViews\.length \?/)
  assert.doesNotMatch(browser, /modePlusOpen/)
})

test('filesystem header expands the shared left sidebar and toggles the right inspector', () => {
  assert.match(browser, /cordis\.sidebar\.collapsed/)
  assert.match(browser, /!viewsOpen \?/)
  assert.match(browser, /data-testid="header-sidebar-expand"/)
  assert.match(browser, /biu:expand-shell-sidebar/)
  assert.match(browser, /data-testid="fsdb-inspector-toggle"/)
  assert.match(browser, /biu:inspector-toggle/)
  assert.match(browser, /biu:shell-layout/)
  assert.doesNotMatch(browser, /setInspectorOpen\(\(prev\) => !prev\)/)
  assert.doesNotMatch(browser, /aria-hidden'\) !== 'true'\)/)
  assert.match(
    browser,
    /inspectorOpen \?\s*\(\s*<ChevronDoubleRightIcon[\s\S]*:\s*\(\s*<ChevronDoubleLeftIcon/,
  )
})

test('database extras sit after the record detail, not in the inspector', () => {
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const style = readFileSync(resolve(import.meta.dirname, './fsdb-style.ts'), 'utf8')
  assert.doesNotMatch(page, /biu:inspector-open/)
  assert.match(page, /slots\.place\('inspector-panels'/)
  assert.match(page, /view\?\.inspector/)
  assert.match(page, /seedCollection: path/)
  assert.match(page, /tabLabel: current\?\.view\?\.title/)
  assert.doesNotMatch(page, /tabLabel: '数据库'/)
  assert.doesNotMatch(page, /RecordPanePanel/)
  assert.match(detail, /fsdb-detail-float-nav/)
  assert.match(detail, /fsdb-detail-more/)
  assert.match(detail, /chrome\?\.DetailTools/)
  assert.match(detail, /按视图顺序切换记录/)
  assert.match(detail, /fsdb-detail-float-btn/)
  assert.match(browser, /findViewNeighbor/)
  assert.match(browser, /stepViewRecord/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*background:#202020/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*width:24px/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*position:sticky/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*top:50%/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*margin:0 0 0 -24px/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*translate\(-28px,-50%\)/)
  assert.match(style, /\.fsdb-detail-float-nav\{[^}]*opacity:0/)
  assert.match(style, /\.fsdb-detail-float-nav::before\{[^}]*left:0/)
  assert.doesNotMatch(style, /\.fsdb-detail-float-nav\{[^}]*position:absolute/)
  assert.match(style, /\.fsdb-detail-float-btn\{[^}]*z-index:1/)
  assert.match(style, /\.heading-outline-host\{[^}]*width:120px/)
  assert.match(style, /\.fsdb-detail-float-nav:hover,\.fsdb-detail-float-nav:focus-within,\.fsdb-detail-float-nav:has\(\[aria-expanded=true\]\)\{[^}]*opacity:1/)
  assert.match(style, /\.fsdb-detail-screen\{[^}]*width:100%/)
  assert.match(style, /\.fsdb-detail-float-btn\{[^}]*width:24px/)
  assert.match(style, /\.fsdb-detail-float-btn\{[^}]*color:#F0EFED/)
  assert.match(style, /\.fsdb-detail-float-btn svg\{[^}]*width:16px/)
  assert.doesNotMatch(style, /border-radius:999px/)
  assert.match(detail, /<h1 className="fsdb-detail-title">/)
  assert.match(detail, /data-testid="fsdb-detail-delete"/)
  assert.match(browser, /onDelete=\{canDelete/)
  assert.match(detail, /<HeadingOutline enabled=\{headingOutline\} \/>/)
  assert.doesNotMatch(browser, /headingOutline=\{collectionPath !== '\/sessions'\}/)
  const outline = readFileSync(resolve(import.meta.dirname, './heading-outline.tsx'), 'utf8')
  assert.match(outline, /closest\('\.fsdb-detail-stage'\)/)
  assert.match(outline, /scrollOutlineTarget/)
  assert.doesNotMatch(outline, /CONTENT_JUMP_EVENT/)
  assert.doesNotMatch(outline, /blockElBySnippet/)
  assert.doesNotMatch(outline, /document\.querySelector\('\.fsdb-detail-main'\)/)
  assert.match(style, /\.heading-outline-host\{[^}]*z-index:20/)
  assert.match(detail, /FOCUS_RECORD_CONTENT/)
  assert.match(detail, /focusRecordTitleNear/)
  assert.match(detail, /mainRef/)
  assert.match(detail, /shouldLeaveTitleForContent/)
  assert.match(detail, /shouldLeaveContentForTitle/)
  assert.doesNotMatch(detail, /<h2 className="fsdb-detail-title-input">/)
  assert.match(style, /\.fsdb-detail-main\{[^}]*padding:0 0 24px/)
  assert.match(style, /\.fsdb-main > \.fsdb-detail-title-row\{[^}]*flex:none/)
  assert.match(style, /\.fsdb-main\{[^}]*padding:0 0 16px/)
  assert.match(style, /\.fsdb-main > :not\(\.fsdb-page-banner\)\{[^}]*max-width:var\(--dsw-chat-max-width\)/)
  assert.match(style, /\.fsdb-detail-main > :not\(\.fsdb-page-banner\)\{[^}]*max-width:var\(--dsw-chat-max-width\)/)
  assert.match(style, /\.fsdb-page-banner\{[^}]*width:100%/)
  assert.match(style, /\.fsdb-detail-title\{[^}]*font-size:32px/)
  assert.match(browser, /<h1 className="fsdb-detail-title">\{activeView\?\.name \?\? title\}<\/h1>/)
  assert.match(browser, /savedViewRecordPath\(collectionPath, activeViewId\)/)
  assert.match(browser, /isReadOnlyViewId\(activeViewId\)/)
  assert.match(browser, /<PageBanner/)
  assert.match(browser, /<PageBanner[\s\S]*writable=\{Boolean\(activeViewId\)\}/)
  assert.doesNotMatch(browser, /<BannerTitleActions/)
  assert.doesNotMatch(detail, /<BannerTitleActions/)
  assert.match(detail, /<PageBanner[\s\S]*writePatch\(selected, \{ banner: next \}\)/)
  assert.match(style, /\.fsdb-page-banner\{[^}]*height:240px/)
  assert.match(style, /\.fsdb-page-banner\.is-empty\{[^}]*height:80px/)
  assert.match(style, /\.fsdb-page-banner:hover \.fsdb-banner-title-actions/)
  assert.doesNotMatch(style, /\.fsdb-detail-title-row:hover \.fsdb-banner-title-actions/)
  const bannerUi = readFileSync(resolve(import.meta.dirname, './page-banner.tsx'), 'utf8')
  assert.match(bannerUi, /添加背景/)
  assert.match(bannerUi, /<PhotoIcon/)
  assert.match(bannerUi, /data-testid="fsdb-banner-open"/)
  assert.match(bannerUi, /<div className="fsdb-banner-pop"/)
  assert.doesNotMatch(bannerUi, /forwardRef/)
  assert.doesNotMatch(bannerUi, /静态背景/)
  assert.doesNotMatch(bannerUi, /动态背景/)
  assert.match(bannerUi, /onTab\('html'\)/)
  assert.match(bannerUi, /onTab\('htmlframe'\)/)
  assert.match(bannerUi, /创建新背景/)
  assert.match(bannerUi, /我的/)
  assert.match(bannerUi, /fsdb-banner-mine-del/)
  assert.match(bannerUi, /删除背景/)
  assert.match(bannerUi, /getPick/)
  assert.match(bannerUi, /fsdb-banner-story/)
  assert.match(bannerUi, /createPortal/)
  assert.match(bannerUi, /fsdb-banner-fly/)
  assert.match(bannerUi, /fsdb-banner-remix/)
  assert.match(bannerUi, /askRemixBanner/)
  assert.match(bannerUi, /二创/)
  assert.match(style, /\.fsdb-banner-story\{/)
  assert.match(style, /\.fsdb-banner-fly\{/)
  assert.match(style, /\.fsdb-banner-remix\{/)
  assert.match(browser, /<TableGlyph icon=\{currentTable\?\.view\?\.icon\}/)
  assert.match(style, /\.fsdb-detail-title-icon\{[^}]*display:inline-flex/)
  assert.match(style, /\.fsdb-detail-title-icon\{[^}]*align-items:center/)
  assert.match(style, /\.fsdb-detail-title-icon\{[^}]*height:36px/)
  assert.match(style, /\.fsdb-detail-title-icon \.fsdb-record-emoji\{[^}]*height:100%/)
  assert.match(detail, /<DetailTitleIcon/)
  assert.match(detail, /recordPreviewEmoji\(selected\)/)
  assert.match(detail, /Icon=\{chrome\?\.Icon\}/)
  assert.match(detail, /<Icon record=\{record\} \/>/)
  assert.match(detail, /<PageBanner/)
  assert.match(detail, /writePatch\(selected, \{ banner: next \}\)/)
  assert.match(style, /\.fsdb-page-banner\{[^}]*height:240px/)
  assert.match(detail, /writePatch\(selected, \{ emoji: next \}\)/)
  assert.match(detail, /fsdb:change/)
  assert.match(browser, /<RecordMark/)
  assert.match(browser, /tableIcon=\{currentTable\?\.view\?\.icon\}/)
  assert.match(browser, /function TableRecordIcon/)
  assert.match(browser, /<RecordEmojiBoard/)
  assert.match(browser, /writePatch\(row, \{ emoji: normalizeRecordEmoji\(next\) \}\)/)
  assert.match(detail, /data-testid=\{`fsdb-pane-\$\{pane\.id\}`\}/)
  assert.match(style, /\.fsdb-fileview\{[^}]*min-height:0/)
  assert.match(style, /\.fsdb-fileview\{[^}]*max-height:none/)
  assert.match(style, /\.fsdb-fileview\{[^}]*overflow:visible/)
  assert.match(style, /\.fsdb-fileview-pre\{[^}]*overflow:visible/)
  assert.match(style, /\.fsdb-fileview-pre\{[^}]*max-height:none/)
  assert.match(style, /\.fsdb-fileview-img\{[^}]*max-height:none/)
  assert.match(style, /\.fsdb-right-body\{[^}]*overflow:auto/)
  assert.match(browser, /app-pane-in/)
  assert.doesNotMatch(browser, /nested \? undefined : 'app-pane-in'/)
  assert.match(browser, /key=\{nested \? 'embed' : `\$\{collectionPath\}:\$\{detailId \?\? ''\}`\}/)
  assert.match(style, /\.fsdb-detail-split\{[^}]*overflow:visible/)
  assert.doesNotMatch(style, /\.fsdb-fileview-pre\{[^}]*overflow:auto/)
  assert.doesNotMatch(style, /\.fsdb-fileview\{[^}]*min-height:240px/)
  assert.doesNotMatch(style, /\.fsdb-fileview-img\{[^}]*max-height:420px/)
  assert.match(browser, /embed \?/)
  assert.doesNotMatch(browser, /setRecordFocus/)
})

test('inspector embed does not poll the collection on an interval', () => {
  assert.match(browser, /const timer = nested/)
  assert.match(browser, /\? 0/)
})

test('switching tables does not remount the whole browser', () => {
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.doesNotMatch(page, /key=\{currentPath\}/)
})

test('list polling pauses while a record is open', () => {
  assert.match(browser, /if \(detailIdRef\.current\) \{/)
  assert.match(browser, /pullDetailBody\(\)/)
  assert.match(browser, /}, 800\)/)
})

test('open detail still reloads body when the collection changes', () => {
  assert.match(browser, /if \(detailIdRef\.current\) \{/)
  assert.match(browser, /pullDetailBody\(\)/)
  assert.match(browser, /pullDetailRecord\(\)/)
  assert.match(browser, /banner: row\.banner \?\? null/)
  assert.match(browser, /window.dispatchEvent\(new Event\('fsdb:change'\)\)/)
})

test('agent view writes reload saved views without a full page refresh', () => {
  assert.match(browser, /pendingViews/)
  assert.match(browser, /SAVED_VIEW_EVENT/)
  assert.match(browser, /adoptViewRef/)
  assert.match(browser, /void syncViewsRef\.current\(\)/)
  assert.match(browser, /await pullSavedViews\(\)/)
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  assert.match(page, /viewsTouched/)
  assert.match(page, /reveal\?\.viewId/)
  assert.match(page, /applyDatabaseChannelPayload\(payload, sessionId\)/)
  assert.match(page, /CustomEvent\('fsdb:change'/)
})

test('collection reload does not follow callback identity', () => {
  assert.match(browser, /const reloadKey = /)
  assert.match(browser, /void reloadRef\.current\(\)/)
  assert.doesNotMatch(browser, /void reload\(\)\s*\n\s*\}, \[reload\]/)
  assert.match(browser, /const EMPTY_FILTERS/)
  assert.doesNotMatch(browser, /lockedFilters = \{\}/)
  assert.match(browser, /void pullFacets\(\)/)
  assert.doesNotMatch(browser, /pullFacets\(\),\s*\n\s*\]\)/)
})

test('pager keeps the current page when filter objects are only recreated', () => {
  const page = readFileSync(resolve(import.meta.dirname, './index.tsx'), 'utf8')
  const inspector = readFileSync(resolve(import.meta.dirname, './inspector-database.tsx'), 'utf8')
  assert.match(browser, /const queryFiltersKey = JSON.stringify\(queryFilters\)/)
  assert.match(browser, /\[fetchQuery, queryFiltersKey, sortField, sortDir, pageSize, collectionPath, dataPath\]/)
  assert.doesNotMatch(browser, /\[fetchQuery, queryFilters, sortField/)
  assert.match(browser, /tables\s*\n\s*\.map\(\(table\) => table\.path\)/)
  assert.doesNotMatch(browser, /tablePathsKey = tables\.map/)
  assert.match(page, /lockedFiltersFromSearch\?\.\(location\.search\) \?\? EMPTY_FILTERS/)
  assert.doesNotMatch(page, /lockedFiltersFromSearch\?\.\(location\.search\) \?\? \{\}/)
  assert.match(inspector, /lockedFiltersFromSearch\?\.\(search\) \?\? EMPTY_FILTERS/)
  assert.doesNotMatch(inspector, /lockedFiltersFromSearch\?\.\(search\) \?\? \{\}/)
})

test('missing sort field falls back to title, not updatedAt', () => {
  assert.match(browser, /sortFields.find\(\(item\) => item.key === 'title'\)/)
  assert.doesNotMatch(browser, /item.kind === 'datetime' \? 'desc'/)
  assert.match(browser, /<SortQueryMenu/)
  assert.match(browser, /<FilterQueryMenu/)
  assert.match(browser, /QUERY_NEST_IGNORE/)
  assert.match(browser, /ignoreSelector=\{QUERY_NEST_IGNORE\}/)
  const menus = readFileSync(resolve(import.meta.dirname, './query-menus.tsx'), 'utf8')
  assert.match(menus, /fsdb-query-grip/)
  assert.match(menus, /@dnd-kit\/core/)
  assert.match(menus, /DragOverlay/)
  assert.match(menus, /useSortable/)
  assert.doesNotMatch(menus, /draggable/)
  assert.match(menus, /moveList/)
  const editor = menus.slice(menus.indexOf('function FilterGroupEditor'))
  assert.match(editor, /添加筛选条件/)
  assert.match(editor, /添加筛选分组/)
  assert.match(editor, /emptyFilterGroup\(\)/)
})

test('widget collection uses the grouped-rectangles glyph, not the plugin puzzle', () => {
  const glyphs = readFileSync(resolve(import.meta.dirname, './table-glyph.tsx'), 'utf8')
  assert.match(glyphs, /name === 'rectangle-group'/)
  assert.match(glyphs, /<RectangleGroupIcon/)
})

test('page collection uses a document glyph, not the table/database icon', () => {
  const glyphs = readFileSync(resolve(import.meta.dirname, './table-glyph.tsx'), 'utf8')
  assert.match(glyphs, /name === 'document' \|\| name === 'document-text' \|\| name === 'page'/)
  assert.match(glyphs, /<DocumentIcon/)
})

test('boolean field glyph is a checkbox, not the document list icon', () => {
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  assert.match(cells, /kind === 'boolean'\) return <span aria-hidden className="fsdb-field-bool-glyph"><BoolBox on=\{false\}/)
  assert.doesNotMatch(cells, /kind === 'boolean'\) return <ClipboardDocumentListIcon/)
})

test('facet field glyph matches the collection stack icon', () => {
  const glyphs = readFileSync(resolve(import.meta.dirname, './table-glyph.tsx'), 'utf8')
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  const spec = readFileSync(resolve(import.meta.dirname, '../host/facets-collection.ts'), 'utf8')
  assert.match(spec, /icon: 'rectangle-stack'/)
  assert.match(glyphs, /name === 'rectangle-stack'/)
  assert.match(glyphs, /<RectangleStackIcon/)
  assert.match(cells, /kind === 'facet'\) return <RectangleStackIcon/)
  assert.doesNotMatch(cells, /kind === 'facet'\) return <TagIcon/)
})

test('row actions reload even when updatedAt is unchanged', () => {
  assert.match(browser, /function recordsFingerprint\(rows/)
  assert.match(browser, /return JSON.stringify\(rows\)/)
  assert.match(browser, /quietUntil\.current = 0\s*\n\s*await reload\(\)/)
})

test('row actions hover the registered action label', () => {
  assert.match(browser, /data-dock-tip=\{action\.label\}/)
  const cells = readFileSync(resolve(import.meta.dirname, './fsdb-cells.tsx'), 'utf8')
  assert.match(cells, /data-dock-tip=\{label\}/)
  const plugin = readFileSync(resolve(import.meta.dirname, '../../../core-plugin-system/src/web/chrome.tsx'), 'utf8')
  assert.match(plugin, /data-dock-tip=\{action\.label\}/)
})

test('inspector no longer listens for add/copy view actions', () => {
  assert.doesNotMatch(browser, /biu:inspector-action/)
  assert.doesNotMatch(browser, /detail === 'add-view'/)
  assert.doesNotMatch(browser, /detail === 'copy-view'/)
})

test('database inspector tab expands crumbs when selected, without a toggle', () => {
  const tab = readFileSync(resolve(import.meta.dirname, './inspector-database.tsx'), 'utf8')
  assert.match(tab, /onClose\?: \(\) => void/)
  assert.match(tab, /data-testid="inspector-tab-close"/)
  assert.match(tab, /inspector-crumb-close/)
  assert.match(tab, /XMarkIcon/)
  assert.match(tab, /inspector-crumb-actions/)
  assert.match(tab, /allowMenu=\{Boolean\(active\)\}/)
  assert.doesNotMatch(tab, /inspector-crumb-toggle/)
  assert.doesNotMatch(tab, /trailOpen/)
  assert.doesNotMatch(tab, /is-crumb-open/)
  assert.match(tab, /is-agent-working/)
  assert.match(tab, /fsdb-agent-follow/)
  assert.match(tab, /isInspectorPaneAbandoned/)
  assert.match(tab, /isInspectorPaneAbandoned\(paneId\)/)
})

test('inspector crumbs lock the first level to an icon', () => {
  const tab = readFileSync(resolve(import.meta.dirname, './inspector-database.tsx'), 'utf8')
  const trail = readFileSync(resolve(import.meta.dirname, './crumb-trail.tsx'), 'utf8')
  const browser = readFileSync(resolve(import.meta.dirname, './browser.tsx'), 'utf8')
  assert.match(tab, /loadRecords\(collection, activeViewId\)/)
  assert.match(tab, /href.split\('\?'\)/)
  assert.match(tab, /peekRecord/)
  assert.match(trail, /lockRootCrumb/)
  assert.match(trail, /rootLocked/)
  assert.match(trail, /fsdb-crumb-btn is-static/)
  assert.match(trail, /lockRootCrumb && index === 1/)
  assert.doesNotMatch(browser, /lockRootCrumb/)
})

test('Escape does not pop record detail back to the list crumb', () => {
  assert.doesNotMatch(browser, /if \(event.key === 'Escape'\) setDetailId\(null\)/)
  assert.doesNotMatch(browser, /window.addEventListener\('keydown', onKey\)/)
})

test('collection header has a layout config control next to the star', () => {
  assert.match(browser, /data-testid="fsdb-layout-toggle"/)
  assert.match(browser, /data-testid="fsdb-layout-menu"/)
  assert.match(browser, /data-testid="fsdb-layout-max"/)
  assert.match(browser, /data-testid="fsdb-layout-full"/)
  assert.match(browser, /AdjustmentsHorizontalIcon/)
  assert.match(browser, /persistPageWidth\('full'\)/)
  assert.match(browser, /is-full-width/)
})
