import { test } from 'vitest'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { parseSharePath } from '../packages/core-file-system/src/share-snapshot.ts'

test('share hrefs skip the full workstation boot', () => {
  assert.equal(Boolean(parseSharePath('/share/abc')), true)
  assert.equal(Boolean(parseSharePath('/share/abc/r/1')), true)
  assert.equal(parseSharePath('/database/pages'), null)
  assert.equal(parseSharePath('/'), null)
})

test('share mount picks content chrome by collection', () => {
  const mount = readFileSync(resolve(import.meta.dirname, './share-mount.tsx'), 'utf8')
  assert.match(mount, /shareChromeFor/)
  assert.doesNotMatch(mount, /chrome=\{\{ Content: PageEditor \}\}/)
  const chrome = readFileSync(resolve(import.meta.dirname, './share-chrome.ts'), 'utf8')
  assert.match(chrome, /collection === '\/sessions'/)
  assert.match(chrome, /sessionsChrome/)
  assert.match(chrome, /PageBlockContent/)
  assert.match(chrome, /SkillsContent/)
  assert.match(chrome, /PageEditor/)
})

test('share mount loads page plugins without booting the workstation', () => {
  const mount = readFileSync(resolve(import.meta.dirname, './share-mount.tsx'), 'utf8')
  assert.match(mount, /applyStoredTheme/)
  assert.match(mount, /bootShareRuntime/)
  assert.match(mount, /loadSharePagePlugins/)
  const plugins = readFileSync(resolve(import.meta.dirname, './share-plugins.ts'), 'utf8')
  assert.match(plugins, /pageEditor/)
  assert.match(plugins, /\/api\/share\/\$\{encodeURIComponent\(token\)\}\/plugin\//)
  const page = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/web/share-page.tsx'), 'utf8')
  assert.match(page, /loadPlugins/)
  assert.match(page, /CrumbTrail/)
  assert.match(page, /PageBanner/)
  assert.match(page, /ShareViewQueryBar/)
  assert.match(page, /loadShareQuery/)
  assert.match(page, /persistPageWidth/)
  assert.match(page, /ShareListTable/)
  assert.match(page, /fsdb-workspace/)
  assert.match(page, /app-pane-in/)
  assert.match(page, /fsdb-share-pager/)
  assert.match(page, /PagerSizeControl/)
  assert.match(page, /aria-label="上一页"/)
  assert.match(page, /aria-label="下一页"/)
  assert.match(page, /ShareCell/)
  assert.match(page, /onPrev=/)
  assert.match(page, /headingOutline/)
  assert.match(page, /fsdb-right-body/)
  assert.match(page, /fsdb-detail-title/)
  assert.match(page, /aria-label="刷新"|onRefresh/)
  assert.doesNotMatch(page, /clipboard\.writeText/)
  const style = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/web/fsdb-style.ts'), 'utf8')
  assert.match(style, /html\.share \.fsdb-detail-float-nav/)
  const table = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/web/share-table.tsx'), 'utf8')
  assert.match(table, /tasks-table-stage/)
  assert.match(table, /fsdb-check-rail/)
  const bar = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/web/share-view-bar.tsx'), 'utf8')
  assert.match(bar, /aria-label="可见列"/)
  assert.match(bar, /sortCustom \? <span className="tasks-sort-dot"/)
  assert.match(bar, /filterActive \? <span className="tasks-filter-dot"/)
  const shareCols = bar.slice(bar.indexOf('aria-label="可见列"'), bar.indexOf('aria-label="表格配置"'))
  const shareConfig = bar.slice(bar.indexOf('aria-label="表格配置"'), bar.indexOf('aria-label="刷新"'))
  assert.doesNotMatch(shareCols, /tasks-sort-dot|tasks-filter-dot/)
  assert.doesNotMatch(shareConfig, /tasks-sort-dot|tasks-filter-dot/)
  assert.match(bar, /表格显示/)
  assert.match(bar, /查看模式/)
  assert.match(bar, /aria-label="刷新"/)
  const detail = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/web/record-detail.tsx'), 'utf8')
  assert.match(detail, /if \(!onPrev && !onNext && !showMore\) return null/)
  assert.doesNotMatch(detail, /if \(readOnly \|\| \(!onPrev && !onNext && !showMore\)\)/)
  assert.match(detail, /writable=\{Boolean\(spec\.writable\) && !readOnly\}/)
  const payload = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/host/share-payload.ts'), 'utf8')
  assert.match(payload, /pluginIds: resources\.pluginIds/)
  assert.doesNotMatch(payload, /share\.sharePlugins \? resources\.pluginIds/)
  const popover = readFileSync(resolve(import.meta.dirname, '../packages/core-file-system/src/web/share-popover.tsx'), 'utf8')
  assert.match(popover, /mintSharePin/)
  assert.match(popover, /sharePlugins/)
})
